drm/radeon: fix compilation error
Fixes below compilation error:
conflicting types for ‘r100_debugfs_mc_info_init’

Fixes: 6f8672d6523bfe38e ("drm/radeon: do not use drm middle layer for
debugfs")
Signed-off-by: Nirmoy Das <nirmoy.das@amd.com>
Reported-by: Mark Broadworth <Mark.Broadworth@amd.com>
Reviewed-by: Christian König <christian.koenig@amd.com>
Acked-by: Alex Deucher <alexander.deucher@amd.com>