Revert "drm/amdgpu: enable swiotlb for gmc 10.0"
This reverts commit 9227ad7f2edd2114eac5855c4668556d27e374a2.

Compiling failed due to drm_need_swiotlb declaration missing:
drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c: In function ‘gmc_v10_0_sw_init’:
drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c:983:23: error: implicit declaration of function ‘drm_need_swiotlb’ [-Werror=implicit-function-declaration]
  983 |  adev->need_swiotlb = drm_need_swiotlb(44);

Signed-off-by: Aaron Liu <aaron.liu@amd.com>